### ISSUE TITLE
a.has-token() function

### ISSUE THREAD

**Issue by johncrim** [oddbird/accoutrement#48]
In addition to the [existing token inspection functions](https://www.oddbird.net/accoutrement/docs/core-inspect.html), please consider adding a function for determining if a token is defined. 

We're using SASS modules for our code, so all the members prefixed with `_` (or `-`) are not accessible.

Here's an example that I think justifies this request. Starting with this example map:

```scss
@use 'accoutrement' as a;

$colors: (
  'form-field': (
    'active': (
      border: #2200ddaa,
      background: #ddd
    )
  )
);
@include a.add-colors($colors);
```

I want to be able to test whether a token exists:

```scss
.form-field {
  @if a.has-token(a.$colors, 'form-field->active->border') {
     &:focus {
        border: 2px solid a.color('form-field->active->border');
     }
  }
}
```

As a workaround I can use something like:
```scss
  @if a.get-token(a.$colors, 'form-field->active->border') != 'form-field->active->border' {
     &:focus {
        border: 2px solid a.color('form-field->active->border');
     }
  }
}
```

but that seems suboptimal (both syntax-wise, and it doesn't handle the possibility that a token path and token value could legitimately be the same). Using sass:map really isn't viable b/c I'd have to repeat the parsing logic.

What do you think?
