### ISSUE TITLE
get-token returns key string when $handle-missing-keys = 'null'

### ISSUE THREAD

**Issue by johncrim** [oddbird/accoutrement#59]
Given the following 2 tests, the first test fails, and the second test passes:

```scss
 $map: (
    'foo': (
      'baz': 2
    )
  )

  @include it('Returns null when root key missing if null mode is enabled') {
    $handle-missing-keys: 'null' !global;

    @include assert-equal(
      get-token($map, 'missing'),
      null
    );

    $handle-missing-keys: 'silent' !global;
  }

  @include it('Returns null when sub-key missing if null mode is enabled') {
    $handle-missing-keys: 'null' !global;

    @include assert-equal(
      get-token($map, 'foo->missing'),
      null
    );

    $handle-missing-keys: 'silent' !global;
  }
```

It appears that the code path is different for root keys vs nested keys. Since I have a test, I'll attempt to provide a fix.
