### ISSUE TITLE
tokens.get() returns null for some present values (4.0.0-beta2)

### ISSUE THREAD

**Issue by johncrim** [oddbird/accoutrement#99]
I'm in the process of updating our codebase to use the new accoutrement (version 4.0.0-beta2), and I found an odd error that occurs in some situations. In short, `tokens.get()` returns `null` sometimes, when there is a value in the map. I haven't been able to figure out the cause yet, but I've narrowed it down to 2 very similar cases, one of which works as expected, and one of which doesn't.

Here's a unit test showing the problematic behavior:

```scss

    @include it('Handles CSS values in maps') {
      $gradients: (
        'accent': linear-gradient(hsl(31deg 94% 52%) 10%, hsl(288deg 95% 62%) 55%, hsl(274deg 95% 57%) 80%),
        'accent2': linear-gradient(orange 10%, magenta 55%, violet 80%)
      );

      @include assert() {
        @include output() {
          background-image: tokens.get($gradients, 'accent');
        }
        @include expect() {
          background-image: linear-gradient(hsl(31deg 94% 52%) 10%, hsl(288deg 95% 62%) 55%, hsl(274deg 95% 57%) 80%);
        }
      }
    }

```

I'm running this test in `test/tokens/_api.scss` in the accoutrement tests, on the `modules` branch - so using all the current build dependencies.

In the above case, the `tokens.get()` call returns `null`. If I change the `tokens.get()` key from `'accent'` to `'accent2'` then `tokens.get()` returns the expected value.

I'll dig into this further, but wanted to report it.
